config/routes.rb
EliteAdultReviews::Application.routes.draw do
  match 'search/:query' => 'search#search'
  match 'niche/:niche' => 'niche#niche'
  namespace :admin do
      resources :ratings
      resources :sites
      resources :categories
      resources :users
  end

 
  scope "/admin" do 
    resources :categories
    resources :sites
    resources :ratings
    resources :prices
    resources :sub_ratings
    resources :screenshots
    resources :users
  end

  resources :categories

  match 'admin/' => 'admin/top#index'
  match ':name/' => 'reviews#show'
  match '/' => 'main#index'
  match '/:controller(/:action(/:id))'
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :category
	belongs_to :site
	validates_uniqueness_of :category_id, :scope => :site_id
end

app/controllers/admin/ratings_controller.rb
class Admin::RatingsController < AdminAreaController
  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
	if params[:site_id].nil?
	flash[:invalid] = "Must specify site."
	redirect_to "/admin/sites"
	return
	end

	@site = Site.find(params[:site_id].to_i)
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.xml
  def create
    @rating = Rating.new(params[:rating])



    respond_to do |format|
      if @rating.save
        flash[:success] = 'Rating was successfully created.'
        format.html { redirect_to("/admin/sites/#{@rating.site_id}") }
        format.xml  { render :xml => @rating, :status => :created, :location => @rating }
      else
	@site = Site.find(params[:rating][:site_id].to_i)
        format.html { render :action => "new" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        flash[:success] = 'Rating was successfully updated.'
        format.html { redirect_to("/admin/sites/#{@rating.site_id}") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to(ratings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/admin/ratings/edit.html.erb
<div id="innercontent">
<h2>Update Rating</h2>
<Br>

<%= error_messages_for :rating %>

<%= form_for(@rating) do |f| %>
  <p>
    <b>Site</b><br />
	<%= @rating.site.display_url %>
  </p>
<br/>
  <p>
    <b>Category</b><br />
	<%= @rating.category.name %>
  </p>
<br/>


  <p>
    <b>Rating</b><br />
	<select name="rating[rating]">
	<% 100.times do |t| %>
		<% t = t +1 %>
		<option value="<%= t %>" <% if @rating.rating == t %>SELECTED<%end%>><%= t %></option>
	<% end %>
	</select>
  </p>
<br/>

  <p>
    <%= f.submit "Save Changes" %>
  </p>

<br/>
<% end %>
<a href="/admin/sites">Back</a>
</div>

app/views/admin/ratings/index.html.erb
<div id="innercontent">

<h2>Recent ratings</h2>

<table>
  <tr>
    <th>Category</th>
    <th>Site</th>
    <th>Rating</th>
  </tr>

<% for rating in @ratings %>
  <tr>
    <td><%=h rating.category_id %></td>
    <td><%=h rating.site_id %></td>
    <td><%=h rating.rating %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br style="clear: both;" />

<a href="/admin/ratings/new">Add A New Rating</a>
</div>

app/views/admin/ratings/new.html.erb
<div id="innercontent">
<h2>New rating</h2>

<%= error_messages_for :rating %>

<%= form_for(@rating) do |f| %>
  <p>
    <b>Site</b><br />
	<%= @site.display_url %>
	<input type="hidden" name="rating[site_id]" value="<%= @site.id %>" />
  </p>

  <p>
    <b>Category</b><br />
	<%= collection_select(:rating, :category_id, Category.all, :id, :name) %>
  </p>


  <p>
    <b>Rating</b><br />
	<select name="rating[rating]">
	<% 100.times do |t| %>
		<% t = t +1 %>
		<option value="<%= t %>" <% if @rating.rating == t %>SELECTED<%end%>><%= t %></option>
	<% end %>
	</select>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>
<a href="/admin/ratings">Back</a>
</div>

app/views/admin/ratings/show.html.erb
<p>
  <b>Category:</b>
  <%=h @rating.category_id %>
</p>

<p>
  <b>Site:</b>
  <%=h @rating.site_id %>
</p>

<p>
  <b>Rating:</b>
  <%=h @rating.rating %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>