config/routes.rb
EliteAdultReviews::Application.routes.draw do
  match 'search/:query' => 'search#search'
  match 'niche/:niche' => 'niche#niche'
  namespace :admin do
      resources :ratings
      resources :sites
      resources :categories
      resources :users
  end

 
  scope "/admin" do 
    resources :categories
    resources :sites
    resources :ratings
    resources :prices
    resources :sub_ratings
    resources :screenshots
    resources :users
  end

  resources :categories

  match 'admin/' => 'admin/top#index'
  match ':name/' => 'reviews#show'
  match '/' => 'main#index'
  match '/:controller(/:action(/:id))'
end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/controllers/admin/prices_controller.rb
class Admin::PricesController < AdminAreaController
  # GET /prices
  # GET /prices.xml
  def index
    @prices = Price.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @prices }
    end
  end

  # GET /prices/1
  # GET /prices/1.xml
  def show
    @price = Price.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @price }
    end
  end

  # GET /prices/new
  # GET /prices/new.xml
  def new
    @price = Price.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @price }
    end
  end

  # GET /prices/1/edit
  def edit
    @price = Price.find(params[:id])
  end

  # POST /prices
  # POST /prices.xml
  def create
    @price = Price.new(params[:price])

    respond_to do |format|
      if @price.save
        flash[:notice] = 'Price was successfully created.'
        format.html { redirect_to(@price) }
        format.xml  { render :xml => @price, :status => :created, :location => @price }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @price.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prices/1
  # PUT /prices/1.xml
  def update
    @price = Price.find(params[:id])

    respond_to do |format|
      if @price.update_attributes(params[:price])
        flash[:notice] = 'Price was successfully updated.'
        format.html { redirect_to(@price) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @price.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.xml
  def destroy
    @price = Price.find(params[:id])
    @price.destroy

    respond_to do |format|
      format.html { redirect_to(prices_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/admin/prices/edit.html.erb
<h1>Editing price</h1>

<%= error_messages_for :price %>

<%= form_for(@price) do |f| %>
  <p>
    <b>Site</b><br />
    <%= f.text_field :site_id %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_field :description %>
  </p>

  <p>
    <b>Price</b><br />
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/admin/prices/index.html.erb
<h1>Listing prices</h1>

<table>
  <tr>
    <th>Site</th>
    <th>Description</th>
    <th>Price</th>
  </tr>

<% for price in @prices %>
  <tr>
    <td><%=h price.site_id %></td>
    <td><%=h price.description %></td>
    <td><%=h price.price %></td>
    <td><%= link_to 'Show', price %></td>
    <td><%= link_to 'Edit', edit_price_path(price) %></td>
    <td><%= link_to 'Destroy', price, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New price', new_price_path %>

app/views/admin/prices/new.html.erb
<h1>New price</h1>

<%= error_messages_for :price %>

<%= form_for(@price) do |f| %>
  <p>
    <b>Site</b><br />
    <%= f.text_field :site_id %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_field :description %>
  </p>

  <p>
    <b>Price</b><br />
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', prices_path %>

app/views/admin/prices/show.html.erb
<p>
  <b>Site:</b>
  <%=h @price.site_id %>
</p>

<p>
  <b>Description:</b>
  <%=h @price.description %>
</p>

<p>
  <b>Price:</b>
  <%=h @price.price %>
</p>


<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>