config/routes.rb
EliteAdultReviews::Application.routes.draw do
  match 'search/:query' => 'search#search'
  match 'niche/:niche' => 'niche#niche'
  namespace :admin do
      resources :ratings
      resources :sites
      resources :categories
      resources :users
  end

 
  scope "/admin" do 
    resources :categories
    resources :sites
    resources :ratings
    resources :prices
    resources :sub_ratings
    resources :screenshots
    resources :users
  end

  resources :categories

  match 'admin/' => 'admin/top#index'
  match ':name/' => 'reviews#show'
  match '/' => 'main#index'
  match '/:controller(/:action(/:id))'
end

app/models/sub_rating.rb
class SubRating < ActiveRecord::Base
end

app/controllers/admin/sub_ratings_controller.rb
class SubRatingsController < ApplicationController
  # GET /sub_ratings
  # GET /sub_ratings.xml
  def index
    @sub_ratings = SubRating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sub_ratings }
    end
  end

  # GET /sub_ratings/1
  # GET /sub_ratings/1.xml
  def show
    @sub_rating = SubRating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sub_rating }
    end
  end

  # GET /sub_ratings/new
  # GET /sub_ratings/new.xml
  def new
    @sub_rating = SubRating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sub_rating }
    end
  end

  # GET /sub_ratings/1/edit
  def edit
    @sub_rating = SubRating.find(params[:id])
  end

  # POST /sub_ratings
  # POST /sub_ratings.xml
  def create
    @sub_rating = SubRating.new(params[:sub_rating])

    respond_to do |format|
      if @sub_rating.save
        flash[:notice] = 'SubRating was successfully created.'
        format.html { redirect_to(@sub_rating) }
        format.xml  { render :xml => @sub_rating, :status => :created, :location => @sub_rating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sub_rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sub_ratings/1
  # PUT /sub_ratings/1.xml
  def update
    @sub_rating = SubRating.find(params[:id])

    respond_to do |format|
      if @sub_rating.update_attributes(params[:sub_rating])
        flash[:notice] = 'SubRating was successfully updated.'
        format.html { redirect_to(@sub_rating) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sub_rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_ratings/1
  # DELETE /sub_ratings/1.xml
  def destroy
    @sub_rating = SubRating.find(params[:id])
    @sub_rating.destroy

    respond_to do |format|
      format.html { redirect_to(sub_ratings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sub_ratings_helper.rb
module SubRatingsHelper
end

app/views/admin/sub_ratings/edit.html.erb
<h1>Editing sub_rating</h1>

<%= error_messages_for :sub_rating %>

<%= form_for(@sub_rating) do |f| %>
  <p>
    <b>Exclusivity</b><br />
    <%= f.text_field :exclusivity %>
  </p>

  <p>
    <b>Updates</b><br />
    <%= f.text_field :updates %>
  </p>

  <p>
    <b>Originality</b><br />
    <%= f.text_field :originality %>
  </p>

  <p>
    <b>Quality</b><br />
    <%= f.text_field :quality %>
  </p>

  <p>
    <b>Speed</b><br />
    <%= f.text_field :speed %>
  </p>

  <p>
    <b>Quantity</b><br />
    <%= f.text_field :quantity %>
  </p>

  <p>
    <b>Design</b><br />
    <%= f.text_field :design %>
  </p>

  <p>
    <b>Navigation ease</b><br />
    <%= f.text_field :navigation_ease %>
  </p>

  <p>
    <b>Features</b><br />
    <%= f.text_field :features %>
  </p>

  <p>
    <b>Price</b><br />
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @sub_rating %> |
<%= link_to 'Back', sub_ratings_path %>

app/views/admin/sub_ratings/index.html.erb
<h1>Listing sub_ratings</h1>

<table>
  <tr>
    <th>Exclusivity</th>
    <th>Updates</th>
    <th>Originality</th>
    <th>Quality</th>
    <th>Speed</th>
    <th>Quantity</th>
    <th>Design</th>
    <th>Navigation ease</th>
    <th>Features</th>
    <th>Price</th>
  </tr>

<% for sub_rating in @sub_ratings %>
  <tr>
    <td><%=h sub_rating.exclusivity %></td>
    <td><%=h sub_rating.updates %></td>
    <td><%=h sub_rating.originality %></td>
    <td><%=h sub_rating.quality %></td>
    <td><%=h sub_rating.speed %></td>
    <td><%=h sub_rating.quantity %></td>
    <td><%=h sub_rating.design %></td>
    <td><%=h sub_rating.navigation_ease %></td>
    <td><%=h sub_rating.features %></td>
    <td><%=h sub_rating.price %></td>
    <td><%= link_to 'Show', sub_rating %></td>
    <td><%= link_to 'Edit', edit_sub_rating_path(sub_rating) %></td>
    <td><%= link_to 'Destroy', sub_rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New sub_rating', new_sub_rating_path %>

app/views/admin/sub_ratings/new.html.erb
<h1>New sub_rating</h1>

<%= error_messages_for :sub_rating %>

<%= form_for(@sub_rating) do |f| %>
  <p>
    <b>Exclusivity</b><br />
    <%= f.text_field :exclusivity %>
  </p>

  <p>
    <b>Updates</b><br />
    <%= f.text_field :updates %>
  </p>

  <p>
    <b>Originality</b><br />
    <%= f.text_field :originality %>
  </p>

  <p>
    <b>Quality</b><br />
    <%= f.text_field :quality %>
  </p>

  <p>
    <b>Speed</b><br />
    <%= f.text_field :speed %>
  </p>

  <p>
    <b>Quantity</b><br />
    <%= f.text_field :quantity %>
  </p>

  <p>
    <b>Design</b><br />
    <%= f.text_field :design %>
  </p>

  <p>
    <b>Navigation ease</b><br />
    <%= f.text_field :navigation_ease %>
  </p>

  <p>
    <b>Features</b><br />
    <%= f.text_field :features %>
  </p>

  <p>
    <b>Price</b><br />
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', sub_ratings_path %>

app/views/admin/sub_ratings/show.html.erb
<p>
  <b>Exclusivity:</b>
  <%=h @sub_rating.exclusivity %>
</p>

<p>
  <b>Updates:</b>
  <%=h @sub_rating.updates %>
</p>

<p>
  <b>Originality:</b>
  <%=h @sub_rating.originality %>
</p>

<p>
  <b>Quality:</b>
  <%=h @sub_rating.quality %>
</p>

<p>
  <b>Speed:</b>
  <%=h @sub_rating.speed %>
</p>

<p>
  <b>Quantity:</b>
  <%=h @sub_rating.quantity %>
</p>

<p>
  <b>Design:</b>
  <%=h @sub_rating.design %>
</p>

<p>
  <b>Navigation ease:</b>
  <%=h @sub_rating.navigation_ease %>
</p>

<p>
  <b>Features:</b>
  <%=h @sub_rating.features %>
</p>

<p>
  <b>Price:</b>
  <%=h @sub_rating.price %>
</p>


<%= link_to 'Edit', edit_sub_rating_path(@sub_rating) %> |
<%= link_to 'Back', sub_ratings_path %>